[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todo_list_addr= "c4d29a9a833c21e9a32b395a7d2dfe9c166c163195d872f421be9c61f3089ebe"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
